"""
Export Service - Exports plans to various formats (PDF, JSON)
"""
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO

def export_plan_to_pdf(plan):
    """Export plan to PDF format"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor='#1a4780',
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor='#2c5aa0',
        spaceAfter=10,
    )
    normal_style = styles['Normal']
    normal_style.fontSize = 10
    normal_style.leading = 14
    
    story = []
    
    # Title
    story.append(Paragraph("Cybersecurity Plan", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Plan metadata
    framework_name = plan.framework.name if plan.framework else "N/A"
    story.append(Paragraph(f"<b>Framework:</b> {framework_name}", normal_style))
    story.append(Paragraph(f"<b>Plan ID:</b> {plan.planId}", normal_style))
    story.append(Paragraph(f"<b>Status:</b> {plan.status}", normal_style))
    story.append(Paragraph(f"<b>Created:</b> {plan.created_at.strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    if plan.completed_at:
        story.append(Paragraph(f"<b>Completed:</b> {plan.completed_at.strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    
    story.append(Spacer(1, 0.3*inch))
    story.append(PageBreak())
    
    # Summary
    if plan.summary:
        story.append(Paragraph("Plan Summary", heading_style))
        # Split summary into paragraphs
        summary_paragraphs = plan.summary.split('\n\n')
        for para in summary_paragraphs:
            if para.strip():
                story.append(Paragraph(para.strip().replace('\n', '<br/>'), normal_style))
                story.append(Spacer(1, 0.1*inch))
    else:
        story.append(Paragraph("Plan Summary", heading_style))
        story.append(Paragraph("Plan summary not yet generated.", normal_style))
    
    story.append(Spacer(1, 0.2*inch))
    story.append(PageBreak())
    
    # Responses
    if plan.responses:
        story.append(Paragraph("Detailed Responses", heading_style))
        story.append(Spacer(1, 0.1*inch))
        
        for response in sorted(plan.responses, key=lambda x: x.timestamp):
            prompt = response.prompt
            if prompt:
                story.append(Paragraph(f"<b>{prompt.category}</b>", normal_style))
                story.append(Paragraph(f"<i>Question:</i> {prompt.text}", normal_style))
                story.append(Paragraph(f"<i>Response:</i> {response.value}", normal_style))
                story.append(Spacer(1, 0.15*inch))
    
    # Footer
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(f"<i>Generated by CyPlanAI - © 2025 CodeRise</i>", normal_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

def export_plan_to_json(plan):
    """Export plan to JSON format"""
    return {
        'planId': plan.planId,
        'framework': plan.framework.to_dict() if plan.framework else None,
        'status': plan.status,
        'summary': plan.summary,
        'created_at': plan.created_at.isoformat() if plan.created_at else None,
        'completed_at': plan.completed_at.isoformat() if plan.completed_at else None,
        'responses': [r.to_dict() for r in plan.responses],
        'metadata': {
            'total_responses': len(plan.responses),
            'exported_at': plan.updated_at.isoformat() if plan.updated_at else None
        }
    }

